import { Typography } from '@material-ui/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

const ProductListPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Listagem de Produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
        Produtos
      </Typography>
      Listagem de produtos



     
    </div>
  )
}

export default ProductListPage
